### ISSUE TITLE
Schema diff from two different platforms

### ISSUE THREAD

**Issue by ablunier** [doctrine/dbal#2285]
First of all, I know that maybe this is not the right place to answer this, but I did it also on stackoverflow a couple months ago http://stackoverflow.com/questions/33307578/doctrine-dbal-retrieving-schema-diff-from-two-different-platforms

Is it possible to compare schemas from two different platforms? Or am I trying to do something that's not possible with Doctrine DBAL? Or could it be an issue?

The code is the following:

``` php
/** @var Doctrine\DBAL\Schema\Schema $fromSchema */
$fromSchema = $mySqlSchemaManager->createSchema();
/** @var Doctrine\DBAL\Schema\Schema $toSchema */
$toSchema = $sqlLiteSchemaManager->createSchema();

$comparator = new \Doctrine\DBAL\Schema\Comparator\Comparator();
$schemaDiff = $comparator->compare($fromSchema, $toSchema);

$diffStatements = $schemaDiff->toSql($mySqlPlatform);
```

And when there are some differences, like if I add a new column on the SQLite schema, I get a lot of changes on the other columns on the `$diffStatements`: DROP FOREIGN KEYs, DROP INDEXes, CHANGE columns (with no real changes), CHANGE columns setting COLLATE BINARY.

**Comment by deeky666** [comment]
@ablunier in theory this should be possible but due to the nature of vendors implementing SQL standard very differently and each of them supporting different features, it is practically not possible. As seen in your example, SQLite does not support foreign key constraints while MySQL does so the comparator generates undesired diffs.
There *might* be possibilities to optimize this but due to the comparator being platform agnostic, unfortunately we can't improve much here. Making the comparator platform agnostic might have been a mistake in design and could be reevaluated for 3.0. If that change in design would happen, we could investigate whether we can support such scenarios but as of 2.x this is unsupported.
