### ISSUE TITLE
dbname should be required paramater for driver

### ISSUE THREAD

**Issue by jkuchar** [doctrine/dbal#2379]
Current state can lead into unexpected WTFs.

For example PostgreSQL driver when no dbname provided database `template1` is used, that means that you will modify default empty database -> every new database will contain your data. (and that schema is not visible in pgAdmin by default)

Therefore `dbname` **should be required parameter**. When you forget to set database name (this was my case) in configuration you will get exception.

Currect behaviour is probably not a bug but *UX fail*.

**Comment by kimhemsoe** [comment]
Not all drivers use "dbname" and an empty dbname is also used for connecting but not selecting a database so we can ex. create a new database.

In the postgresql case we changed the default database to "postgresql". So that should "solve" issues where the template database is getting modified.

https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php#L89

**Comment by jkuchar** [comment]
Thanks for reply. "fixed" in d99bc394f13ee2827f2dc10dba3fea0ba532661e
