### ISSUE TITLE
Request of PostgreSQL94Platform

### ISSUE THREAD

**Issue by zhanghuanchong** [doctrine/dbal#2452]
The class "PostgreSQL94Platform" isn't involved in version 2.5.4. But in the latest document (v2.5.4 too), it says it's available:
http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/platforms.html

Is it possible to release a small new version, such as 2.5.5, with PostgreSQL94Platform?

Thank you.

**Comment by deeky666** [comment]
The "latest" docs always refer to `master` branch because it is built from that branch. I have to confess this can be a bit confusing. I'm sorry but we won't add the new platform to `2.5` branch as it is a new feature and `2.5` only receives bug fixes. You will have to wait until `2.6` is out which *SHOULD* not take too long anymore.
