### ISSUE TITLE
Wrong sequence name generator

### ISSUE THREAD

**Issue by andreas4all** [doctrine/dbal#2505]
Hi,

I created entity like this:

```
/**
 * @ORM\Entity
 */
class WirelessStatisticsServiceShortTerm
{
    /**
     * @var int
     *
     * @ORM\Column(name="wireless_statistic_id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;

... shortened ...
}
```

Doctrine use this sequence:

```
wireless_statistics_service_short_term_wireless_statistic_id_se
```

and PostgreSQL generate this:

```
wireless_statistics_service_short_ter_wireless_statistic_id_seq
```

https://github.com/doctrine/doctrine2/issues/6032

**Comment by mareeo** [comment]
I'm guessing the fix for this would be modifying this. 
https://github.com/doctrine/dbal/blob/3ebe5d77bbf33dee8ee6db805c7ef3c56c06cb55/src/Platforms/PostgreSQL94Platform.php#L202

PostgreSQL seems to truncate long sequence names to 59 characters and then appends `_seq` from what I've seen. Doctrine does no sequence name truncation which results in it querying non-existent sequence.

The fix at this point is to switch to to the SEQUENCE generated value strategy and specify the sequence name. Using your example:

```
/**
 * @ORM\Entity
 */
class WirelessStatisticsServiceShortTerm
{
    /**
     * @var int
     *
     * @ORM\Column(name="wireless_statistic_id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="SEQUENCE")
     * @ORM\SequenceGenerator(sequenceName="wireless_statistics_service_short_ter_wireless_statistic_id_seq")
     */
    protected $id;

... shortened ...
}
```

**Comment by morozov** [comment]
Should have been fixed by https://github.com/doctrine/dbal/pull/4106.
