### ISSUE TITLE
Schema migration table name checks are case insensitive

### ISSUE THREAD

**Issue by dhensby** [doctrine/dbal#2710]
When integrating the doctrine/dbal into a project I wanted to provide DB schema migrations for database tables names that had changed case. (eg: MyTable -> mytable) however the `Schema` migration logic compares tables in a case-insensitive manner.

The `Schema\Comparator` checks if tables exist by using `Table::getShortestName()` or `Schema::getFullQualifiedAssetName()`, which both perform `strtolower` on the value they return.

I'd expect the behaviour to either recognise that there are two separate tables or to attempt a table rename in this scenario, instead they are treated as the same table.

**Comment by Ocramius** [comment]
Many databases such as DB2, Postgres and SqlServer handle table name casing
by upper-casing/lower-casing automatically during introspection, so we
*cannot* really add case sensitivity to the comparator, as it's just asking
for trouble. If you have duplicate symbols with different casing, for your
and for our mental sanity, consider dropping them.

On 3 May 2017 22:37, "Daniel Hensby" <notifications@github.com> wrote:

When integrating the doctrine/dbal into a project I wanted to provide DB
schema migrations for database tables names that had changed case. (eg:
MyTable -> mytable) however the Schema migration logic compares tables in a
case-insensitive manner.

The Schema\Comparator checks if tables exist by using
Table::getShortestName() or Schema::getFullQualifiedAssetName(), which both
perform strtolower on the value they return.

I'd expect the behaviour to either recognise that there are two separate
tables or to attempt a table rename in this scenario, instead they are
treated as the same table.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/doctrine/dbal/issues/2710>, or mute the thread

**Comment by dhensby** [comment]
Thanks for the reply. We have a feature where table names that are improperly cased are renamed to the correct case. This is mostly to deal with users who move MySQL databases from a windows environment (case insensitive DB table names) to a linux one (case sensitive table names). Do you have any advice on how I could mimic this feature with the dbal library?

**Comment by Ocramius** [comment]
> Do you have any advice on how I could mimic this feature with the dbal library?

Not really - you will likely need a manual migration here, as the tooling reaches its limits.

**Comment by dhensby** [comment]
Ok - thanks. I've encountered this problem to a greater degree with our PostgreSQL test suite where we need to ensure every identifier is quoted (which we do anyway) but I've learnt we can't rely on dbal's feature of only quoting reserved words because it appears that PostgreSQL will store quoted identifiers literally (ie: keeping case) and unquoted identifiers as lowercase. So if you create a table as `CREATE TABLE SomeTable` and then do `SELECT * FROM "SomeTable"` an error will be thrown by the database where "SomeTable" doesn't exist.

It seems to me that the "lazy quoting", while well intentioned, does have side-effects that could be mitigated simply by quoting all identifiers as standard. Is there a reason this is avoided at the moment?

**Comment by dhensby** [comment]
OK - thanks - those docs  specifically about doctrine ORM. The limitation of not being able to quote join table names, is that specific to dbal or could I quote join table names if I need to?

FYI - the context here is that I'm looking at [replacing the database layer in SilverStripe](https://github.com/silverstripe/silverstripe-framework/issues/6632) so we may have manoeuvrability around limitations in doctrine ORM unless they are actual limitations of dbal.

I'm going to advocate for moving to lowercase table identifiers but that might be a hard battle to win.

**Comment by Ocramius** [comment]
>  could I quote join table names if I need to?

Yes, you can quote anything, but it's opt-in. We will likely switch to quoting as opt-out in 3.x, but we don't know how much this will impact applications such as your one.

 > I'm going to advocate for moving to lowercase table identifiers but that might be a hard battle to win.

It's the only sane choice - I don't see a reason to have casing in table/columns/indexes.

**Comment by dhensby** [comment]
> It's the only sane choice - I don't see a reason to have casing in table/columns/indexes.

It's basically for legacy reasons

Ok, thanks for your help on this - I'll close this off now :)
