### ISSUE TITLE
Join is not working with update query

### ISSUE THREAD

**Issue by JefferyHus** [doctrine/dbal#2716]
```php
			DB::init();

			$q = DB::build()->update('requests', 'r')
			->join('r','visitors', 'v', 'r.visitor = v.id')
			->set('r.captcha = :success')
			->where('v.ip LIKE :ip')
			->andWhere('blocked = 2')
			->setParameter(':ip', Input::ip())
			->setParameter(':success', $dataObject->success)->getSQL();
			$this->container->logger->error($q);

			DB::destroy();
```
Using a custom DB class I call doctrine/dbal query builder, so in this piece of code I was expecting to see the join string when I log the `getSQL()` function but what I get as result is this `UPDATE requests r SET r.captcha = :success =  WHERE (v.ip LIKE :ip) AND (blocked = 2)` as you can see before WHERE there is just a simple "=" sign but not the full JOIN string.
am I doing something wrong

**Comment by Ocramius** [comment]
Joins aren't​supported in update statements in many vendors, as far as I
know. This should probably throw an exception.

On 6 May 2017 6:55 p.m., "Jeffery ThaGintoki" <notifications@github.com>
wrote:

			DB::init();			$q = DB::build()->update('requests',
'r')			->join('r','visitors', 'v', 'r.visitor =
v.id')			->set('r.captcha = :success')			->where('v.ip LIKE
:ip')			->andWhere('blocked = 2')			->setParameter(':ip',
Input::ip())			->setParameter(':success',
$dataObject->success)->getSQL();			$this->container->logger->error($q);			DB::destroy();

Using a custom DB class I call doctrine/dbal query builder, so in this
piece of code I was expecting to see the join string when I log the getSQL()
function but what I get as result is this UPDATE requests r SET r.captcha =
:success = WHERE (v.ip LIKE :ip) AND (blocked = 2) as you can see before
WHERE there is just a simple "=" sign but not the full JOIN string.
am I doing something wrong

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/doctrine/dbal/issues/2716>, or mute the thread

**Comment by JefferyHus** [comment]
But is there any luck to have a support for joins in the delete and update queries? or I must always use two queries a select then update or delete?

**Comment by Ocramius** [comment]
You can do it by using a query built manually, without the query builder.

**Comment by JefferyHus** [comment]
yeah that's a solution too, hope there will be a support for it in the next days, thanks anyway :+1:

**Comment by Ocramius** [comment]
@JefferyHus don't think so: we don't support features that aren't available cross-platform.

Leaving open, as I think an exception should be thrown early in this scenario

**Comment by JefferyHus** [comment]
```php
$q  = "UPDATE `requests` SET `captcha` = :captcha WHERE (visitor = :visitor) AND (blocked = 2) ORDER BY `created_at` DESC LIMIT 1";
$st = DB::connection()->prepare($q);
$st->bindParam(':captcha', $dataObject->success, \PDO::PARAM_BOOL);
$st->bindParam(':visitor', $v['id'], \PDO::PARAM_INT);
$st->execute();
```

I have tried this one again, no exceptions thrown but it does not work, this query have been tested directly in mysql console and it works perfectly.

**Comment by Ocramius** [comment]
Yes, I'm saying that DBAL should throw an exception when you try an `->update()`, `->insert()` or `->delete()` with a `->join()`

**Comment by JefferyHus** [comment]
well yes it does throw an exception, but there was an issue that I couldn't check as i had no time, is that in the update query builder it adds a "=" without joins or any unsupported closure, but then moved to `->executeUpdate()` which finally did the job I was waiting. :+1:

**Comment by Ocramius** [comment]
I think something is lost in translation :-P

Additional exceptions should be added to DBAL, so that it *ACTIVELY*
prevents you from calling ->join(), and crashes *BEFORE* attempting to
execute this kind of query.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

On Tue, May 9, 2017 at 2:07 AM, Jeffery ThaGintoki <notifications@github.com

**Comment by JefferyHus** [comment]
Or mention it in the documentation so people can know at least.

**Comment by morozov** [comment]
Closing due to the lack of interest in addressing the issue.
