### ISSUE TITLE
JSON type without encoding/decoding

### ISSUE THREAD

**Issue by Tobion** [doctrine/dbal#2723]
The JSON datatype (see #2653) automatically encodes/decodes the JSON datastructure. We need a JSON datatype that does not do this for several reasons:
- It's easier to switch existing text columns to json as we can keep using strings
- Sometimes you get JSON and just want to save it. It doesn't make sense to decode it, just so that doctrine can encode it again when inserting.
- More flexibility by being able to use any different serializations, e.g. using JMS serializer or `json_decode($data, false)` instead of `json_decode($data, true)` which is hard-coded into the JSON type.

So I'd propose to rename the new `json` type to `json_decoded` and introduce a new `json` type that uses a plain json string internally without transformation.
I chose `json_decoded` because you effectively work with a decoded json structure all the time (similar to old json_array). json_decoded would be more correct because it does not need to be an array. It can also be null or a string or int etc. decoded from json.

**Comment by Tobion** [comment]
An alternative name for `json_decoded` would be `json_data`

**Comment by jvasseur** [comment]
I would prefer to keep the current type name `json`. Maybe a non-decoded type could be name `json_string`.

**Comment by Ocramius** [comment]
Agree: json for the introduced type, json_string if you really need a
string (and tbh, I don't see why json_string would be in core)

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by Tobion** [comment]
json_string  as name does not make sense to me because it's not clear if it's a decoded string from json or a raw json string. json_array was also a decoded array.

>  I don't see why json_string would be in core

I gave three reasons above. Also DBAL is just an abstraction over DB access. So it's more logical to have a plain JSON type than a magic JSON column that decodes and encodes magically. Otherwise you could add alot more types with different serialization forms.

**Comment by jvasseur** [comment]
`json_string` seems logical to me, it's a string containing json, but I agree with @Ocramius not sure if it should be in core.

I'm against renaming the json type for a few reasons:
 - it feels like most common use case is to want a decoded json rather than an non-decoded json string (to store free form data).
 - the PR introducing the type was merge nearly 2 year ago, there is probably some project already using it (even if it never was in a released version).
 - some package exists that introduce similar types with the name `json` (one of them is https://github.com/sonata-project/sonata-doctrine-extensions)
 - it is designed as a replacement for `json_array` except it isn't made only for storing arrays so `json` seems logical.
 - doctrine types always return the decoded data (ie: date types return `DateTimeInterface` instances instead of the date string).
