### ISSUE TITLE
Add maximum number of prepared statements to Platform

### ISSUE THREAD

**Issue by sascha-egerer** [doctrine/dbal#2748]
The platform should provide an information how many values can be bound in a prepared statement.

See also
https://stackoverflow.com/questions/6581573/what-are-the-max-number-of-allowable-parameters-per-database-provider-type

**Comment by sascha-egerer** [comment]
Any feedback for this?

**Comment by Ocramius** [comment]
I think this is needed for https://github.com/doctrine/dbal/pull/682 and https://github.com/doctrine/dbal/pull/2762#issuecomment-312482555

**Comment by morozov** [comment]
> The platform should provide an information how many values can be bound in a prepared statement.

I don't agree with this statement. In order to provide this information, the DBAL would have to hard-code it in the platform code which will then turn into a maintenance nightmare like maintaining reserved keywords and maximum identifier lengths currently is.

It should be up to the user to decide how many statements they want to execute in a batch and whether it should depend on the currently used database platform.
