### ISSUE TITLE
After update the package to 2.6.2, an error occurred!

### ISSUE THREAD

**Issue by lincome** [doctrine/dbal#2847]
`laravel 5.4
[2017-09-07 09:45:14] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Class Doctrine\DBAL\Driver\PDOStatement contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Doctrine\DBAL\Driver\Statement::errorInfo) in G:\xampp7\htdocs\support.netflying.net\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:28`

**Comment by morozov** [comment]
@lincome it looks weird at a glance since `Doctrine\DBAL\Driver\PDOStatement` [extends `PDOStatement`](https://github.com/doctrine/dbal/blob/v2.6.2/lib/Doctrine/DBAL/Driver/PDOStatement.php#L28)  which in turn [implements `errorInfo()`](http://php.net/manual/en/pdostatement.errorinfo.php). Could you provide some more information on the issue like stack trace or an example script?

I cannot reproduce this issue locally by running `phpunit -c phpunit.xml.dist`. This configuration covers the line in question.

**Comment by lincome** [comment]
Thanks for your help.
I found the answer in [https://github.com/doctrine/dbal/issues/2628](https://github.com/doctrine/dbal/issues/2628)
I also update the php version from 5.6 to 7.1. It may be the cause.The 7.1 version became more strict to the interface

**Comment by morozov** [comment]
@lincome yeah, it seems very much like https://github.com/doctrine/dbal/issues/2628#issuecomment-316865616.

For the sake of getting this resolved and documented, could you do the following:

1. Check if the PDO extension is enabled in your runtime.
2. Check if there's a file in your codebase which declares the `PDOStatement` class in the global namespace.

**Comment by Ocramius** [comment]
Note that the PDO extension is a required dependency since 2.6.0

**Comment by lincome** [comment]
@Ocramius @morozov Great . Thank you.
