### ISSUE TITLE
it looks like this broke in psql 10

### ISSUE THREAD

**Issue by sergiors** [doctrine/dbal#2928]
https://github.com/doctrine/dbal/blob/4f7c1b7231e64e1c0b3ed39136120f9e9bb246fb/lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php#L292

How can I add that line to solve the problem for pgsql 10?
```php
$data = $this->_conn->fetchAll('SELECT min_value, increment_by FROM pg_sequences WHERE sequencename = ' . $this->_platform->quoteIdentifier($sequenceName));
```

**Comment by lcobucci** [comment]
@sergiors we don't support PGSQL 10 yet. There're some PRs discussing and fixing some things but they're blocked for now since Travis doesn't support PGSQL 10 too.

Please go through the recent PRs and check if they already solve this problem. If they do solve it, please close this issue. If not, you'll have some examples on how to fix it (starting with the tests, please).

**Comment by sergiors** [comment]
Thanks @lcobucci I'm following the issue #2893
