### ISSUE TITLE
Binary digit is not valid

### ISSUE THREAD

**Issue by brunorafaeI** [doctrine/dbal#2982]
Hi, I'm having trouble inserting a boolean value of a json object into the database, because the field is of type Bit (Postgresql 9.6) to retrieve values from that field I needed to do a (mapping_types: bit to boolean in doctrine dbal - Symfony 3) and now it is not able to convert boolean to bit in insert. returning this error message:

`Invalid text representation: 7 ERROR:  \"t\" is not a valid binary digit`

Object Json:
`{
    "dtNaissance": "03/06/1983",
    "idAgence": 1,
    "dtEntree": "01/01/2017",
    "isNirProv": true,
}`
I am using a ClassType to try to convert this value, I already used Integer as type, but it fills the field with NULL, and there is no BitType :: class, how could I proceed?

**Comment by Ocramius** [comment]
Sorry, I don't understand the issue.

 * What is the raw value?
 * Is it in the DB or in your PHP process? Are you trying to save it or
load it?
 * What is the involved DBAL type?
 * What is the DBAL type converting it to?

**Comment by brunorafaeI** [comment]
@Ocramius so, as I have already described, I'm trying to insert the information inside the database (Postgresql 9.6) from a JSON object, in this table there is a field of type BIT, which I can recover via Doctrine dbal, but for this I needed to insert a line of the configuration of SYMFONY 3 (mapping_types: bit: boolean), that is, Doctrine has no support for BIT (so I convert to boolean) I'm now having problems to do insert type BOOLEAN because in my conception Doctrine should be able to reconvert this data into BIT automatically

**Comment by Ocramius** [comment]
That's the confusion. I thought you wanted to enter that entire json string in a field.

Doctrine has indeed no support for `BIT`, but writing a postgres-specific type should be feasible. The only problem is that all the examples I find represent a `BIT` type with the explicit cast `B'10101`, for example. You'd need the raw value, since DBAL provides no way to prepend that `B` marker to query parameters.

Related: https://github.com/yiisoft/yii2/issues/7682 (note that https://github.com/Tigrov/yii2-pgsql/blob/master/src/ArrayConverter.php is insecure due to it not using prepared statements)

**Comment by Ocramius** [comment]
Closing here: `BIT` is not to be implemented in DBAL.

**Comment by Tigrov** [comment]
@Ocramius, related to your phrase "note that https://github.com/Tigrov/yii2-pgsql/blob/master/src/ArrayConverter.php is insecure due to it not using prepared statements"

You can see that the class `ArrayConverter` just converts array to string for DB and vice versa. As far as it allows the current implementation of Yii2.
And the result is placed as prepared statement using `$this->setSql($sql)->bindValues($params);`

https://github.com/Tigrov/yii2-pgsql/blob/master/src/QueryBuilder.php#L55
https://github.com/yiisoft/yii2/blob/master/framework/db/Command.php#L469

https://github.com/Tigrov/yii2-pgsql/blob/master/src/QueryBuilder.php#L84
https://github.com/yiisoft/yii2/blob/master/framework/db/Command.php#L541

Or it is quoted using `$schema->quoteValue($value);`
https://github.com/Tigrov/yii2-pgsql/blob/master/src/QueryBuilder.php#L116

So, it does not need to use prepared statements as Yii2 does not use prepared statements when converts values `ColumnSchema::dbTypecast($value)`.
https://github.com/yiisoft/yii2/blob/master/framework/db/ColumnSchema.php#L105
The statements are prepared after.

**Comment by Ocramius** [comment]
@Tigrov thanks for clarifying. Indeed, my mistake here, I thought `ArrayConverter` was building an actual piece of dynamic SQL.
