### ISSUE TITLE
Eliminate dependency on doctrine/common

### ISSUE THREAD

**Issue by Majkl578** [doctrine/dbal#3176]
There's currently hard dependency on `doctrine/common` which pulls unnecessary packages like Lexer or Annotations.
What is actually used:
`Doctrine\Common\Cache` -> to be replaced by `doctrine/cache`
`Doctrine\Common\EventManager` -> needs to be extracted into `doctrine/event-manager`
`Doctrine\Common\Util\Debug` -> move into `doctrine/dbal` / extract to `doctrine/debug` / replace by something else?
`Doctrine\Common\Proxy\Exception\UnexpectedValueException` thrown from `SQLAnywhere16Platform` - this looks like a bug (wrong import)

Blocker for https://github.com/doctrine/migrations/issues/722

**Comment by stof** [comment]
> Doctrine\Common\Util\Debug

Is this one really useful ? This debugging component is quite bad IMO (using it in the past have hurt my debugging, because the dumping has side effects as it initializes collections, which made the bug I was debugging disappear).
I suggest recommending `symfony/var-dumper` instead, which spent lots of effort to ensure it stays side-effect-free

**Comment by Majkl578** [comment]
@stof For the rest of 2.x we'll just import a simplified version of Util\Debug here and let's see what happens for 3.x, we may move console commands outside of main DBAL repo, making it easier to use symfony/var-dumper.
