### ISSUE TITLE
Unnecessary alter sequence queries generated on Oracle db during schema update

### ISSUE THREAD

**Issue by bobvandevijver** [doctrine/dbal#3210]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.7.1

#### Summary

The schema update tool (and migrations) generates `ALTER SEQUENCE` queries for sequence which already have the specified properties. Executing the queries does not have any effect on the database, but the keep being generated.

#### Current behavior

See below (I limited the output to a single query, it actually happens with all our entities:
```
bobvandevijver@web-dev:/var/www/app$ php bin/console doctrine:schema:update --dump-sql

 The following SQL statements will be executed:

     ALTER SEQUENCE user__table_id_seq INCREMENT BY 1;
    <6 more>
bobvandevijver@web-dev:/var/www/app$ php bin/console doctrine:schema:update --force

 Updating database schema...

     7 queries were executed

 [OK] Database schema updated successfully!

bobvandevijver@web-dev:/var/www/app$ php bin/console doctrine:schema:update --dump-sql

 The following SQL statements will be executed:

     ALTER SEQUENCE user__table_id_seq INCREMENT BY 1;
     <6 more>
```

#### How to reproduce

We use a [Oracle express docker container](https://github.com/wnameless/docker-oracle-xe-11g), without specific configuration, only a user for this project. The entities all have the same trait for id configuration:

```php
trait IdTrait
{
  /**
   * @var int|null
   *
   * @ORM\Column(name="id", type="integer")
   * @ORM\Id
   * @ORM\GeneratedValue(strategy="AUTO")
   */
  private $id;

  /**
   * @return int|null
   */
  public function getId(): ?int
  {
    return $this->id;
  }
}
```

The table was created with the following query (from migrations):
```sql
$this->addSql('CREATE SEQUENCE user__table_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1');
```

#### Expected behavior

These queries should be generated, as the sequences already have the specified property set.

(Not sure whether this is the right repository, just let me know if it needs to be moved!)

**Comment by morozov** [comment]
Below are the steps to reproduce the issue using DBAL:
```php
$conn = DriverManager::getConnection([
    'driver' => 'oci8',
    'host' => 'localhost',
    'user' => 'doctrine',
    'password' => 'oracle',
    'dbname' => 'XE',
]);

$schema = new Schema();
$table = $schema->createTable('test');
$table->addColumn('id', 'integer', ['autoincrement' => true]);

$currentSchema = $conn->getSchemaManager()->createSchema();

$queries = $currentSchema->getMigrateToSql($schema, $conn->getDatabasePlatform());
echo implode(";\n\n", $queries), ";\n";
```

On an empty database, on the first run, the scrip produces the following DDL:
```sql
CREATE TABLE test (id NUMBER(10) NOT NULL);

DECLARE
  constraints_Count NUMBER;
BEGIN
  SELECT COUNT(CONSTRAINT_NAME) INTO constraints_Count FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'TEST' AND CONSTRAINT_TYPE = 'P';
  IF constraints_Count = 0 OR constraints_Count = '' THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TEST ADD CONSTRAINT TEST_AI_PK PRIMARY KEY (ID)';
  END IF;
END;;

CREATE SEQUENCE TEST_SEQ START WITH 1 MINVALUE 1 INCREMENT BY 1;

CREATE TRIGGER TEST_AI_PK
   BEFORE INSERT
   ON TEST
   FOR EACH ROW
DECLARE
   last_Sequence NUMBER;
   last_InsertID NUMBER;
BEGIN
   SELECT TEST_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
   IF (:NEW.ID IS NULL OR :NEW.ID = 0) THEN
      SELECT TEST_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
   ELSE
      SELECT NVL(Last_Number, 0) INTO last_Sequence
        FROM User_Sequences
       WHERE Sequence_Name = 'TEST_SEQ';
      SELECT :NEW.ID INTO last_InsertID FROM DUAL;
      WHILE (last_InsertID > last_Sequence) LOOP
         SELECT TEST_SEQ.NEXTVAL INTO last_Sequence FROM DUAL;
      END LOOP;
   END IF;
END;;
```
On the second run, it produces:
```sql
DROP SEQUENCE TEST_SEQ;

DROP INDEX primary;

ALTER TABLE TEST MODIFY (id NUMBER(10) DEFAULT NULL);
```
This DQL attempts to drop the sequence and the primary key but fails because it doesn't use the PK name:
> ORA-01418: specified index does not exist

@bobvandevijver does it look relevant to the problem you're experiencing? If not, please provice some steps to reproduce isolated from ORM and Migrations.

**Comment by bobvandevijver** [comment]
@morozov As far as I can see, not directly, but I took your example and just used these steps to reproduce it with the ORM only.

```php
$conn = DriverManager::getConnection([
    'driver' => 'oci8',
    'host' => 'localhost',
    'user' => 'doctrine',
    'password' => 'oracle',
    'dbname' => 'XE',
]);

$schema = new Schema();
$schema->createSequence('test');

$currentSchema = $conn->getSchemaManager()->createSchema();

$queries = $currentSchema->getMigrateToSql($schema, $conn->getDatabasePlatform());
echo implode(";\n\n", $queries), ";\n";
```

Basically, I've changed your `createTable` call with my `createSequence` call.

The first run results in:
```
CREATE SEQUENCE test START WITH 1 MINVALUE 1 INCREMENT BY 1;
```

The second run (after applying the SQL above:
```
ALTER SEQUENCE test INCREMENT BY 1;
```

Executing the latter statement does not change the outcome of the script (as expected).

**Comment by morozov** [comment]
@bobvandevijver thanks, this is exactly what I was looking for.

**Comment by morozov** [comment]
@bobvandevijver the issue you described in https://github.com/doctrine/dbal/issues/3210#issuecomment-403591542 is reproducible on `v2.7.1` but is not reproducible on `master`. It must have been fixed by https://github.com/doctrine/dbal/pull/3086. Could you please check?

**Comment by bobvandevijver** [comment]
It has indeed been fixed on `master`, and also on `2.7.x-dev` (the MR also described a backport to `2.7`, so I tested both. I missed this MR apparently when I was searching through the issues.

@morozov When can I expect the arrival of the new release for 2.7 (so 2.7.2)?

**Comment by morozov** [comment]
@bobvandevijver I want to release [`2.7.2`](https://github.com/doctrine/dbal/milestone/65) together with [`2.8.0`](https://github.com/doctrine/dbal/milestone/65) in order to have the same set of bug fixes in them. If `2.8.0` doesn't get finalized in the next couple of weeks, I think I can release `2.7.2` alone.

/cc @Majkl578

**Comment by Majkl578** [comment]
I hope we can do the release within days, we sorted out the blockers in ORM. 👍

**Comment by morozov** [comment]
For the record, the issue identified in https://github.com/doctrine/dbal/issues/3210#issuecomment-403239510 doesn't look easy to fix. It also may be not worth fixing unless it affects users.

The thing is, the DBAL schema defines an autoincrement field which is represented with a PK, a sequence and a trigger in the real DB schema.

The problem is that the logical schema (autoincrement) is converted to the physical one (sequence and trigger) on the platform level using plain SQL. Therefore, when it comes to the schema comparison, the engine doesn't understand that the physical representation matches the logical definition and produces an unexpected diff.

Introduction of an intermediate layer between the DBAL schema and the DB schema doesn't look reasonable to fix this only issue.
