### ISSUE TITLE
Nested JOINs

### ISSUE THREAD

**Issue by writteninr3d** [doctrine/dbal#3224]
Hey,

I'm looking for a PHP query builder that supports nested JOINs. For example:

SELECT t1.id FROM t1
LEFT JOIN (t2
    INNER JOIN t3 ON t3.t2id = t2.id)
ON t2.t1id = t1.id

Is there existing or planned support for this feature?

-Ben

**Comment by morozov** [comment]
Technically, the `QueryBuilder` component doesn't limit you in what you can build since almost every piece passed to its methods is a SQL expression, not necessarily an object name:
```php
$builder = $conn->createQueryBuilder();
$builder
    ->from('t1')
    ->select('t1.id')
    ->leftJoin('t1', '(t2 INNER JOIN t3 ON t3.t2id = t2.id)', '', 't2.t1id = t1.id');

// SELECT t1.id FROM t1 LEFT JOIN (t2 INNER JOIN t3 ON t3.t2id = t2.id) ON t2.t1id = t1.id
```

On the other hand, `QueryBuilder::*Join()` methods accept `$fromAlias` as the first argument whose value can be used for building nested joins if there's more than one level of nesting.

The bottom line is: it's a useful but relatively rarely used feature of SQL. If it's possible to implement it in `QueryBuilder` w/o breaking compatibility, we can consider it.

**Comment by writteninr3d** [comment]
Complicated queries are used in several parts of our organisation's app, and I'm trying to make the logic more comprehensible by breaking it into parts that have individual meaning and could be reused in combination with other parts. I would then create each of these parts, and expose them in a user-friendly Advanced Search UI that allows users to combine several parts to make a query. The business logic would use domain knowledge to package up their selections into an appropriately structured query object, before passing it to an actual QueryBuilder to translate into SQL. Since the idea is to create reusable parts, I was hoping to reference separate parts using on-the-fly aliasing, which is why I am trying to avoid injecting SQL directly if possible.

Feel free to comment how realistic you think this goal is - is it just a pipe dream, or have you heard of people successfully achieving this kind of system?

Also, semi-related - I take it that despite the documentation stating that $fromAlias can only reference the from table, it is possible to use $fromAlias to reference a table included in a previous ->join() clause as well? Otherwise, why make $fromAlias a required parameter when it can only reference one value? For example:

    $builder
    ->from('t1')
    ->select('t1.id')
    ->innerJoin('t1', 't2', '', 't2.t1id = t1.id');
    ->innerJoin('t2', 't3', '', 't3.t2id = t2.id');

**Comment by morozov** [comment]
> is it just a pipe dream, or have you heard of people successfully achieving this kind of system?

APIs and queries like this exist in enterprise applications where everything is related to everything out of the box or can be customized this way. Users also can build reports from anything related to anything filtered by anything. The downside of this approach is that depending on complexity, these queries may have poor performance. It's fine to have them designed this way but eventually, some of them end up being optimized in a more case-specific way.

> Also, semi-related - I take it that despite the documentation stating that $fromAlias can only reference the from table, it is possible to use $fromAlias to reference a table included in a previous ->join() clause as well?

In the case of nested joins, the same table (`t2`) can be the joined one from the outer query standpoint and the from one from the standpoint of the nested join. Therefore, if implemented this way, nested joins won't necessarily contradict the documentation.

**Comment by Ocramius** [comment]
Closing here: the solution initially provided by @morozov is correct.

The `QueryBuilder` is pretty much a string assembler, and not much more than that. If we start exploring every feature supported by SQL we will end with an infinite rabbit hole.

I strongly advise *AGAINST* abstracting SQL into snippets with separate responsibilities, because SQL engones, whilst advanced, are still full of optimisation and performance issues that will end up blocking you.

Instead of optimising the single concerns, abstract the queries you want to perform into interfaces (name + parameter+ return type), and focus on writing SQL in *strings* from there (SQL strings are easily introspected and verified via static analysis these days).
