### ISSUE TITLE
Failed AppVeyor build allowed to pass

### ISSUE THREAD

**Issue by Majkl578** [doctrine/dbal#3451]
Right now master has a failing test on AppVeyor, yet the build is marked as successful:
https://ci.appveyor.com/project/doctrine/dbal/builds/22107072/job/ga7em29v6vktoxh2

**Comment by morozov** [comment]
This is most likely because we combine `phpunit` and `ocular` commands as independent ones, as if it was in bash with `set +e`:
https://github.com/doctrine/dbal/blob/92920ede68e1d16246712cd41318dd82bb72c015/.appveyor.yml#L142-L145
We should use something like `set -e` for PowerShell or combine the commands via `&&`.
