### ISSUE TITLE
Enum DBType Return as string

### ISSUE THREAD

**Issue by vishalinfyom** [doctrine/dbal#3492]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.9.2

#### Summary

Here is my code, i have table `xyz` and column `abc` with type enum, while getting column types it will return `string` i think it should be `enum`.

Correct me if i am wrong, Thanks.

```$this->schemaManager = DB::getDoctrineSchemaManager();
$columns = $this->schemaManager->listTableColumns($tableName);

$this->columns = [];
foreach ($columns as $column) {
	if (!in_array($column->getName(), $ignoredFields)) {
		$this->columns[] = $column;
	}
}

 foreach ($this->columns as $column) {
	$type = $column->getType()->getName(); // this is return as string,even its type is enum
}

**Comment by Ocramius** [comment]
This depends on how Doctrine type mappings have been configured in your platform (see https://github.com/doctrine/dbal/blob/546cd67495de87a7406cbdb4580730068c696cab/lib/Doctrine/DBAL/Platforms/MySqlPlatform.php#L1046-L1083)

Closing here, since this is expected/configurable behavior (that out of the box throws an exception for unrecognised `enum` type)
