### ISSUE TITLE
Remove user provided PDO functionality

### ISSUE THREAD

**Issue by jwage** [doctrine/dbal#3545]
See discussion about the functionality here https://github.com/doctrine/dbal/issues/3487

If we remove it, we should maybe add some documentation showing a user how to build something to use an existing PDO connection or offer something outside of doctrine/dbal to solve the use case

**Comment by SenseException** [comment]
Related issue: #3544.

**Comment by morozov** [comment]
Keynotes for the documentation:

1. Persistent connections are already supported, no need for a user-provided connection.
2. In order to share the same `PDO` instances between DBAL and other components, initialize the connection in DBAL and access it using `Connection::getWrappedConnection()->getWrappedConnection()`.
