### ISSUE TITLE
Do 2.9 and 2.10 actually support MariaDB 10.0?

### ISSUE THREAD

**Issue by reedy** [doctrine/dbal#3728]
I see in master (to become 3.0.0), that https://github.com/doctrine/dbal/commit/355d242f4cbc40f5d475c13a5bdbf85a44f35b89 "Remove Postgres 9.3 and MariaDB 10.0 support"

However, if we look at https://www.doctrine-project.org/projects/doctrine-dbal/en/2.10/reference/platforms.html and https://www.doctrine-project.org/projects/doctrine-dbal/en/2.9/reference/platforms.html (and even master actually) seem to suggest "MariaDb1027Platform for version 10.2 (10.2.7 GA) and above."

Are older versions (or unsupported by dbal) of MariaDB just supported using the MySQL drivers? Or something else? Or is it a documentation problem?

If 2.10/2.9 support MariaDB 10.0, why don't the doc pages above say that?

Thanks!

**Comment by Ocramius** [comment]
I can only find that platform in the codebase: IIRC, previous versions used the mysql platform.

**Comment by SenseException** [comment]
Yes, the older MariaDB versions were covered by MySQL platforms, but DBAL won't paying attention to compatibility with MariaDB 10.0 anymore. Because 10.0 isn't actively supported by DBAL and [reached it's end of life](https://mariadb.com/kb/en/library/changes-improvements-in-mariadb-100/), it won't be mentioned in the docs.

MariaDB and MySQL are going to divert from each other more with each version, but they will still have many things in common.
