### ISSUE TITLE
MySqlPlatform::getListTableForeignKeysSQL slow on MySQL 8

### ISSUE THREAD

**Issue by Slamdunk** [doctrine/dbal#4015]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 2.10.2
| PHP | 7.4.6
| MySQL |  8.0.20

See also https://github.com/yiisoft/yii2/issues/17444

#### Summary

`\Doctrine\DBAL\Platforms\MySqlPlatform::getListTableForeignKeysSQL` slow on MySQL 8

https://github.com/doctrine/dbal/blob/c2b8e6e82732a64ecde1cddf9e1e06cb8556e3d8/lib/Doctrine/DBAL/Platforms/MySqlPlatform.php#L187-L199

#### How to reproduce

MySQL changed the implementation of `information_schema` in version 8, and now the above query is considerably slower:

| MySQL version | Elapsed milliseconds |
| - | -
| 5.7 | 0.4 |
| 8.0 | 33.9 |

An `EXPLAIN` query shows a lot of differences:

##### MySQL 5.7 EXPLAIN

![immagine](https://user-images.githubusercontent.com/152236/82449154-1031b680-9aab-11ea-9adb-65a27befb295.png)

##### MySQL 8.0 EXPLAIN

![immagine](https://user-images.githubusercontent.com/152236/82449105-fc865000-9aaa-11ea-9449-a5fd99fd8ea3.png)

**Comment by Slamdunk** [comment]
This is super annoying for our business app, we heavily rely on that query and MySQL 8.0 doubles the resource requirements in our production (for some nightly batches).
Likely it's just our fault as how we shaped the app, but still upgrading from 5.7 to 8.0 would be just a pain without gain.
We're moving to MariaDB 10.4 smoothly: I'll leave the issue open for future readers and willing fixers, but I consider this low-priority.

**Comment by rickschippers** [comment]
A bug report for this issue was filed at bugs.mysql.com as well. They made some improvements to this in the upcoming 8.0.21 release. So that might fix this issue partially or completely.

We've been running into this issue with the concrete5 cms, which is using doctrine and these queries as well. It's runs fine if you have a small amount of databases / tables. But If you have a larger db servers with lots of databases/tables it becomes extremely slow (from a couple seconds on mysql 5.7 to 30+ minutes on mysql 8.0.20).

For reference: https://bugs.mysql.com/bug.php?id=98238

**Comment by rickschippers** [comment]
Just to come back to this. MySQL 8.0.21 was released two days ago. Updating from 8.0.20 to 8.0.21 completely fixed this slowness for me.

**Comment by Slamdunk** [comment]
I haven't tried since we are on MariaDB now, but I can safely assume this issue can be considered superseded.

**Comment by aembler** [comment]
Thanks for following up @rickschippers
