### ISSUE TITLE
RFC: Rename MasterSlaveConnection

### ISSUE THREAD

**Issue by albe** [doctrine/dbal#4052]
I would like to suggest to rename the MasterSlaveConnection extension to something more sensible.
My suggestion would be `PrimaryReplicaConnection`, since that's one version of naming alternatives for the concept that is widely used (https://en.wikipedia.org/wiki/Master/slave_(technology)#Terminology_concerns).

Since this part of the code is primarily concerned about managing connections between writable and readable database replicas it could also be named `WriteReadConnection`, though IMO that could be a bit more misleading.

IF this and a specific naming is agreed upon by the team, I would take on the code part of this change.

For b/c an alias for the old class name could be kept around at least for a bit of time.

**Comment by greg0ire** [comment]
Thanks for proposing this change. I would go with `PrimaryReplicaConnection`. If we are going with an alias, this might help: https://dev.to/greg0ire/how-to-deprecate-a-type-in-php-48cf

Disclaimer though, this method caused us a lot of headaches with `doctrine/persistence`, because types we deprecated were used in signatures. I'm not sure that would be likely here though.

An alternative would be to just not use aliases and copy/paste/improve the class (making it `final`, using private properties, using type declarations). We would then deprecate `MasterSlaveConnection` (and maybe stop maintenance on it?).

**Comment by beberlei** [comment]
yes lets do it, rename it and keep the old class + deprecate + remove in the next major.

**Comment by albe** [comment]
Thanks for the quick feedback and action! Guess this is indeed a good opportunity to not just rename, but deprecate and create an improved version of this connection strategy.

**Comment by beberlei** [comment]
Closed with #7047798
