### ISSUE TITLE
BC Break after removing method \Doctrine\DBAL\Driver\PDOConnection::quote

### ISSUE THREAD

**Issue by Shahelm** [doctrine/dbal#4281]
The problem appeared in releases 2.10.3 [commit](https://github.com/doctrine/dbal/pull/3287/commits/85bc13deb0abbbf3a99347ab9b757c8c1a1ebd96)

The problem is that now, with strict mode enabled, nothing but string cannot be passed to \Doctrine\DBAL\Driver\PDOConnection::quote. These changes break backward compatibility and should not have been recorded as minor changes.

**Comment by greg0ire** [comment]
The removed method had an `{@inheritdoc}` annotation, which means passing something else than a string `Doctrine\DBAL\Driver\PDOConnection::quote` was a violation. So I'd say this is invalid, what do you think @morozov ?

**Comment by Shahelm** [comment]
Small digression:
This change can lead to a TypeError where there was none before.

**Comment by ekosogin** [comment]
I confirm TypeError. Also backward compatibility was brooken

**Comment by greg0ire** [comment]
Phpstan says it's an API violation: https://phpstan.org/r/c7f52e44-e49b-4905-b829-df22ff5cd7f9

**Comment by morozov** [comment]
In this case, the caller deals with a driver connection which happens to be implemented via PDO but should allow passing anything:

https://github.com/doctrine/dbal/blob/b5e15999e8f626b9a50edef142fffc7be57d0211/lib/Doctrine/DBAL/Driver/Connection.php#L31-L39

While it's technically a BC break, there are a few of circumstances:

1. With the release of `2.11.0`, `2.10.x` only accepts security fixes, so we can only fix it in `2.11.x`.
2. The issue is only reproducible in strict mode meaning that the caller opts in passing valid types.
3. It's clearly a bug on the calling side. There's no need to quote integers.

Before fixing it in `2.11.x`, I'd like to see why the reporters would like to get this issue fixed.

**Comment by Shahelm** [comment]
There is no reason for quote an integer, just the old api allowed to do it, the problem was discovered by accident during testing after the update.
