### ISSUE TITLE
Class 'Doctrine\DBAL\Driver\PDOMySql\Driver' not found

### ISSUE THREAD

**Issue by somir-khan** [doctrine/dbal#4439]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.0.0

#### Summary

Class 'Doctrine\DBAL\Driver\PDOMySql\Driver' not found while migration 

#### Previous behaviour

It was working flawlessly

#### How to reproduce
1.composer require doctrine/dbal to upgrade to version 3.0
2.run the migration command

**Comment by greg0ire** [comment]
BC breaks are expected to happen when you release a major version you know… no need to report them. That being said, I don't think you are using the DBAL yourself but through `doctrine/migrations`, that maybe wrongly advertises compatibility with `doctrine/dbal`? To be sure about that, please provide a stack trace. If you don't know how to get one, please read [this guide](https://symfony.com/doc/current/contributing/code/stack_trace.html)

**Comment by amigogobara** [comment]
I have the same issue but I didn't install doctrine/migrations in laravel|
@greg0ire 
Here's my stack trace:
  Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'Doctrine\DBAL\Driver\PDOMySql\Driver' not found

  at /var/www/bookingEngineLaravel/vendor/laravel/framework/src/Illuminate/Database/MySqlConnection.php:64
    60|      * @return \Doctrine\DBAL\Driver\PDOMySql\Driver
    61|      */
    62|     protected function getDoctrineDriver()
    63|     {
  > 64|         return new DoctrineDriver;
    65|     }
    66| }
    67| 

  Exception trace:

  1   Illuminate\Database\MySqlConnection::getDoctrineDriver()
      /var/www/bookingEngineLaravel/vendor/laravel/framework/src/Illuminate/Database/Connection.php:892

  2   Illuminate\Database\Connection::getDoctrineSchemaManager()
      /var/www/bookingEngineLaravel/vendor/laravel/framework/src/Illuminate/Database/Schema/Grammars/ChangeColumn.php:37

**Comment by amigogobara** [comment]
BTW I make a downgrade to version 2.12 and it's working fine @somir-khan

**Comment by somir-khan** [comment]
I did the same .

**Comment by youssefkhouili** [comment]
what is the commend to install version 2.12?

**Comment by amigogobara** [comment]
composer require doctrine/dbal:2.*

**Comment by youssefkhouili** [comment]
Thank you

**Comment by greg0ire** [comment]
@amigogobara I can only transfer issues within the Doctrine org, you should post the issue to Laravel. Before you do so, be sure to learn Github markdown or edit your message to see how I improved the markup so that it's legible.

**Comment by McMazalf** [comment]
> composer require doctrine/dbal:2.*

Thanks :)

**Comment by hajatianapatrick** [comment]
Thank you

**Comment by hngmihai** [comment]
Had the exact same issue & downgrading helped. Thank you!

**Comment by afsarpervez** [comment]
> composer require doctrine/dbal:2.*

Thank you!

**Comment by Dilshan97** [comment]
> BTW I make a downgrade to version 2.12 and it's working fine @somir-khan

it's woking for me

**Comment by neoacevedo** [comment]
I installed the version 3.1 via composer require in L6: same result.

I checked the documentation in laravel: https://laravel.com/docs/6.x/migrations#modifying-columns

Downgrading the version to 2.* did the trick. @greg0ire please, more than one people reporting the same issue is a call of attention.

**Comment by greg0ire** [comment]
@neoacevedo but I have already given this attention, and a proper response:

> you should post the issue to Laravel

Did anybody act on that? If not, please give my messages some attention, folks. I can elaborate in case this was unclear.

In https://github.com/doctrine/dbal/issues/4439#issuecomment-729540505 , we can see that a class present in DBAL 2, and removed in DBAL 3 is referenced from `laravel/framework/src/Illuminate/Database/MySqlConnection.php:64` (there is an alias, but you can see the FQCN here: https://github.com/laravel/framework/blob/43518afa5253600513b19ba7c3d4aad2a3eb69c3/src/Illuminate/Database/MySqlConnection.php#L5)

I see that `doctrine/dbal` is not a hard dependency of `laravel/framework`, otherwise forbidding DBAL 3 would have fixed the issue. They still test that package with the DBAL, but with this constraint: https://github.com/laravel/framework/blob/43518afa5253600513b19ba7c3d4aad2a3eb69c3/composer.json#L81 (DBAL 2). So IMO DBAL 3 was never intended to be supported by L6

IMO a conflict with DBAL > 3.0.0 could have been added to `laravel/framework` v6 to avoid this issue, but now it's a bit late… not much anyone can do in Laravel IMO, and there I think nothing that can be done in the DBAL either, sorry.
