### ISSUE TITLE
Extract some lesser used platforms to separate packages with the goal of dropping support for them

### ISSUE THREAD

**Issue by alcaeus** [doctrine/dbal#4445]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | yes
| BC Break    | no

#### Summary

The list of supported platforms in DBAL is large. While this ensures compatibility with a range of databases, it has several drawbacks:
- every feature added to DBAL requires support of some kind in all platforms
- testing all database platforms on supported PHP versions is requires lots of resources
- it requires knowledge of all supported databases when making changes, which is a large burden on maintainers
- some platforms can't easily be tested as they don't provide free licenses

#### Proposed solution

I propose that we eventually drop support for the following platforms from DBAL:
- DB2 (proprietary software)
- Drizzle (no release since 2012)
- Oracle (proprietary software)
- SQLAnywhere (proprietary software)
- SQLServer (proprietary software)

This would leave the following platforms:
- MariaDB
- MySQL
- PostgreSQL
- Sqlite

I would suggest extracting the logic for these platforms to separate packages and deprecating the original classes. The newly created packages would be included in DBAL 3, but dropped from DBAL 4. For people that use any of the dropped platforms, an upgrade to DBAL 4 would require for them to explicitly depend on the new package and changing some class names. In DBAL 3, deprecation notices let people know of upcoming changes.

Note that as soon as DBAL 4 is released, **no more support is provided for those platforms**. The packages are marked as "abandoned" through packagist. People that rely on these platforms should get in touch about how to help maintaining them in the future.

**Comment by nicolas-grekas** [comment]
I fully support splitting into separate packages. This will allow monitoring installation stats, and the project will be able to figure out which drivers are actually used.
The split could be done via a subtree split as we do on Symfony for eg Mailer.
(I've no opinion about stopping to support the DBs you listed: dunno how much they are used, dunno the burden maintaining them creates.)

**Comment by greg0ire** [comment]
Related:
- SQLAnywhere support has already been removed, some people are trying to get it back and were told to build their own package: https://github.com/doctrine/dbal/pull/4077
- Drizzle support has been dropped too: https://github.com/doctrine/dbal/issues/4445

So it seems we are already moving in that direction.

Regarding the maintenance burden, it's a bit lighter now CI-wise thanks to Github Actions, because Oracle is supported there and that allowed us to drop continuousphp. But review-wise, my lack of knowledge of some of these exotic platforms makes it impossible for me to understand and merge some PRs we receive. I don't know how comfortable @morozov is with those.

> The newly created packages would be included in DBAL 3, but dropped from DBAL 4.

Do you mean required? Because that conflicts with the idea of a subtree split I think (`symfony/mailer` does not require e.g. `symfony/sendgrid-mailer`). I think you mean "maintained as long as `doctrine/dbal` 3 is maintained"?

Anyway, I think it is a good idea for drivers for which we have some doubts, I'm not sure which drivers those are, but SQL Server certainly comes to mind.

**Comment by nicolas-grekas** [comment]
> But review-wise, my lack of knowledge of some of these exotic platforms makes it impossible for me to understand and merge some PRs we receive

on this topic, in Symfony, I usually suppose that ppl that submit PRs on some edge case topics know their thing a bit (that latest being the LDAP component), and are the one affected by any issue and/or fixes. I challenge the PR, try to get feedback from ppl that previously worked on the topic, and merge. I don't need to know everything and can rely on the community :)

**Comment by morozov** [comment]
I fundamentally disagree with this idea. We dropped support for SQL Anywhere and Azure not because we didn't want to support them but because we couldn't, not matter how hard we try (this mostly applies to the former).

I believe that supporting a diverse variety of platforms makes the DB abstraction well-rounded and really abstract. I doubt it's possible to maintain a decent API designed for MySQL and expect it to work for proprietary platforms.

Should we also drop support for Windows?
