### ISSUE TITLE
Symfony compatibility with version 2.13 on PHP 7.1 (An option named "connection" already exists)

### ISSUE THREAD

**Issue by speakpavlov** [doctrine/dbal#4565]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| doctrine/dbal Version     | 2.13.0
| symfony/symfony version |  3.4
#### Summary

After the upgrade from version 2.9.3 to 2.13.0 on PHP 7.1, we got the exception 
```
An option named "connection" already exists.      
```
I guess that is connected to the Symfony version.

#### Current behaviour

```
In InputDefinition.php line 232:
  [Symfony\Component\Console\Exception\LogicException]  
  An option named "connection" already exists.          
```

#### How to reproduce

composer.json with
``` 
"symfony/symfony": "3.4.*",
"doctrine/dbal":"2.13.0"
```

execute:
```
php bin/console 
```
#### Expected behaviour

Expected: No error

**Comment by speakpavlov** [comment]
It's not working on 3.4.26 (last version of 3.4) as well.

**Comment by beberlei** [comment]
@speakpavlov please run the command with `-v` flag and post the full stack trace.

**Comment by Giorgiolino** [comment]
Hello @beberlei .

I happen to experience the same issue too. My dependencies versions are not exactly the same though.
From what I've seen, the issue comes from the input option named "**connection**" that is first defined in command
 https://github.com/doctrine/dbal/blob/2.12.1/lib/Doctrine/DBAL/Tools/Console/Command/RunSqlCommand.php#L55 and further redefined in a child command https://github.com/doctrine/DoctrineBundle/blob/1.11.2/Command/Proxy/RunSqlDoctrineCommand.php#L24 (note: the child command makes the option value...optional)
 
 (EDIT):
 @speakpavlov :
 For what it's worth, I found out that this is already fixed in other versions with this commit https://github.com/doctrine/DoctrineBundle/commit/86d2469d6be06d55ad7b9e2f076f6942476f2e87

**Comment by ostrolucky** [comment]
Not sure what do you expect to happen here. Adding new command options is allowed, similarly as adding new methods to classes is. If new option/method is added in parent that was also defined in subclass by a chance is unfortunate, but there is nothing that can prevent that. Nobody would cover that under their BC promise. That's why I didn't bother to report the issue in DBAL, but fixed that in doctrine-bundle directly.

**Comment by Giorgiolino** [comment]
@ostrolucky I was not aware that the change had happened in the child class first (ie in DoctrineBundle/RunDoctrineSqlCommand).; But knowing that, the **"issue"** makes sense. And for the record, it also appear obvious to me that - given what you said - there is no issue per se on doctrine/dbal side.

**Comment by ostrolucky** [comment]
Ok, let's close it here then. Simply update doctrine-bundle
