### ISSUE TITLE
2.13 `QueryBuilder::execute()` is no longer backwards compatible.

### ISSUE THREAD

**Issue by m50** [doctrine/dbal#4591]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.13

#### Summary

The `QueryBuilder::execute()` function now returns `Doctrine\DBAL\ForwardCompatibility\Result` or `int`, which is no longer compatible with the previous `Doctrine\DBAL\Driver\Statement`, which causes anything requiring a `Doctrine\DBAL\Driver\Statement` to be passed in to break. This is not in the upgrade file, and it is not consistent in the API. Because of this, this broke our ORM built on top of DBAL with a minor version bump (simple composer update).

#### Previous behaviour

`QueryBuilder::execute()` returned `Doctrine\DBAL\Driver\Statement`.

#### Current behavior

`QueryBuilder::execute()` returns `Doctrine\DBAL\ForwardCompatibility\Result` or `int` which cannot be used in places where Statement is needed.

#### How to reproduce

Just require a `\Doctrine\DBAL\Driver\Statement` be passed into a function, and call `execute()` on a query builder instance, and pass it into the function. In 2.12.*, that will work, in 2.13.*, that is broken.

**Comment by mdumoulin** [comment]
Right. We were mislead by documentation where breaking change was consecutively introduced :

Here for Doctrine\DBAL\Connection : https://github.com/doctrine/dbal/commit/df4343721d9981e58afd15eeaf18c885a2399766#diff-425f50e688c77962b97e5fd1f9803a6d9ffa9bf260ba12391f73b2aab14914eeL906

Here for Doctrine\DBAL\Query\QueryBuilder : https://github.com/doctrine/dbal/commit/68f0d99fcf270525b3df59294f277a6643facbf9#diff-829b37fd7ed65c7ead12002f3e689f3a672986dd88fd0f5d4d5f92321a61211dL201

I would say that following method should return an object implementing Doctrine\DBAL\Driver\Statement & Doctrine\DBAL\Result:
- Doctrine\DBAL\Connection::execute()
- ~~Doctrine\DBAL\Connection::executeCacheQuery()~~
- Doctrine\DBAL\Query\QueryBuilder::execute()

It can be achieved by making Doctrine\DBAL\ForwardCompatibility\Result implementing and wrap Doctrine\DBAL\Driver\Statement instead of Doctrine\DBAL\Driver\ResultStatement

Edit : 
It's ok for Doctrine\DBAL\Connection::executeCacheQuery() to return a ResultStatement

**Comment by virtualize** [comment]
There is more code out there that requires a `Doctrine\DBAL\Driver\Statement` instead `Doctrine\DBAL\ForwardCompatibility\Result`. 

I just stumbled upon that one, while composer was updating doctrine/dbal (2.12.1 => 2.13.0)
`Argument 1 passed to Symfony\Component\Security\Acl\Dbal\AclProvider::hydrateObjectIdentities() must implement interface Doctrine\DBAL\Driver\Statement, instance of Doctrine\DBAL\ForwardCompatibility\Result given
`
