### ISSUE TITLE
fetchFirstColumn - not found when searching 3.1 docs

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [doctrine/dbal#4658]
https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/data-retrieval-and-manipulation.html

![image](https://user-images.githubusercontent.com/15625235/119344096-86a55d80-bc97-11eb-8c97-02bf42d52b3d.png)

**Comment by greg0ire** [comment]
Also, for some reason, you linked to data-retrieval-and-manipulation.html . The source of this document is at https://github.com/doctrine/dbal/blob/3.1.x/docs/en/reference/data-retrieval-and-manipulation.rst in case you want to send a pull request.

**Comment by jacekkarczmarczyk** [comment]
> Correct, but that should be reported to the dbal repo instead.

Ah sorry for that, I thought `doctrine-website` repo contains DBAL docs as well

**Comment by morozov** [comment]
I'm still confused whether the issue is about the method missing from the documentation or not searching for it. The method is documented:
https://github.com/doctrine/dbal/blob/891ec185b0a0740a0dfeede0a3eddd2f399bb009/docs/en/reference/data-retrieval-and-manipulation.rst#L179

But I can confirm the search for "fetchFirstColumn" doesn't yield anything, it just hangs. Maybe it's a search/website bug?

**Comment by jacekkarczmarczyk** [comment]
It wasn't there when I created the issue, added about month ago (https://github.com/doctrine/dbal/commit/c0935b610e86eefa7f9ae4b27ce1ee392fcab716)

**Comment by morozov** [comment]
Should we close the issue then?
