### ISSUE TITLE
Connection add interface

### ISSUE THREAD

**Issue by chriskapp** [doctrine/dbal#4678]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

I would suggest to add two new interfaces to the `Connection` class:

```
ReadConnectionInterface
+ fetchAssociative
+ fetchNumeric
+ fetchOne
+ fetchAllNumeric
+ fetchAllAssociative
+ fetchAllKeyValue
+ fetchAllAssociativeIndexed
+ fetchFirstColumn
+ iterateNumeric
+ iterateAssociative
+ iterateKeyValue
+ iterateAssociativeIndexed
+ iterateColumn
```

```
WriteConnectionInterface
+ insert
+ update
+ delete
+ executeStatement
```

This would allow implementations to narrow down the scope of the connection and it would also help to migrate legacy database abstractions to DBAL since they could start to use those interfaces for migration.

In the future this could be also an interesting topic as PSR to define a set of interfaces which describe a standard way how to get data from database much like JDBC API. But as a first step I think it would be great to have those interfaces.

So please let me know your opinions, if there is some interest I could provide a first draft PR.

**Comment by morozov** [comment]
> [...] would also help to migrate legacy database abstractions to DBAL since they could start to use those interfaces for migration.

How is the scope of the interface relevant to migration to DBAL? Since the `Connection` class is not final, you can define the interfaces in your project, introduce a new class that extends the connection and implements the interfaces, and you'll get exactly what this issue is about.

> In the future this could be also an interesting topic as PSR to define a set of interfaces which describe a standard way how to get data from database much like JDBC API.

PDO and the DBAL are already sort of JDBC APIs. Why would there be a need for another standard?

> So please let me know your opinions, if there is some interest I could provide a first draft PR.

I agree that the Connection interface is bloated and effectively describes a God object. But I don't think that just adding interfaces will improve anything. It might help if the God object was broken down into a composition of smaller pieces which would implement smaller interfaces.

As for specifically the read/write separation of concerns, I believe it might be misleading since there's no guarantee that the consumer of `executeQuery()` won't execute an `INSERT`.

**Comment by chriskapp** [comment]
Hi, yes regarding the interface, this would also work as you described, but in the best case I dont want to maintain those interfaces in my project. I would like to say, I want build a connection which fulfils the contract of the DBAL connection, then I can implement those interface at my legacy project and in the future I could swap my implementation with doctrine DBAL.

Regarding JDBC, I see it exactly the same way, that DBAL is basically the standard and I dont want to change the methods etc. so basically this is only a step to formalize the standard by introducing an interface for the `Connection` class. Regarding PSR, it was also just an idea for the future, it would be also possible to create a separate package i.e. `doctrine/contracts` where we could define those interfaces or add them directly to the repo.

Regarding the read/write split, we could also create just a single `ConnectionInterface` which basically extends the read/write interfaces. But I find it charming that a service could declare: I only want to use read methods and ignore the rest of the interface.

Regarding the `executeQuery` method, yes this would be indeed possible but it would feel more like a misuse of the interface since afaik `executeQuery` is for DQL and `executeStatement` for DML/DDL queries, but as said, we could also create a single `ConnectionInterface` without this read/write split.

So I think this change would have no BC and every user could opt in to use those interfaces and it would help in those cases described above. In general I think it is also a good idea to provide an interface for a class so that others could also type-hint this interface instead of the concrete implementation.

**Comment by morozov** [comment]
One of the problems I'd like to potentially solve by introducing a set of wrapper-level connection interfaces is getting rid of the cache being part of the API. Instead, I'd like it to be just a middleware. It might be a good example of a read-only connection. The introduction of the new interfaces as is including copying previous poor design decisions may make these changes even harder.

Don't get me wrong, I'm not opposed to introducing interfaces as such. I just don't believe that introducing interfaces just for the sake of interfaces is good.

**Comment by morozov** [comment]
> I dont want to maintain those interfaces in my project.

As long as the API is stable, there shouldn't be much maintenance.

> I would like to say, I want build a connection which fulfils the contract of the DBAL connection, then I can implement those interface at my legacy project and in the future I could swap my implementation with doctrine DBAL.

And you can totally do it. I'd rather have you learn about all the pros and cons in your project and come back with a proposal based on your experience rather than make DBAL a playground for a legacy migration project.

**Comment by chriskapp** [comment]
No problem, there is no need to rush, if you like we can keep this issue open to grow the idea and see whether there is also some interest from other users and thanks for maintaining this project.

**Comment by rjd22** [comment]
I stumbled upon this issue because I'm using the low level DBAL Connection API for the project I'm working on and was actually thinking about writing integration tests for my query repositories. I don't use any mocking library but write my own mock objects for this.

Sadly there is no edge(interface) in DBAL available base my Mock on so I can make sure my tests fail when something changed in the DBAL integration point.

Ofcourse I can wrap the DBAL connection class and add an interface there. But this doesn't allow you to test integration with the DBAL interface.

I understand this it really unimportant in comparison with all the other awesome work you're doing on DBAL but it would really improve developer experience.

**Comment by derrabus** [comment]
> I stumbled upon this issue because I'm using the low level DBAL Connection API for the project I'm working on and was actually thinking about writing integration tests for my query repositories. I don't use any mocking library but write my own mock objects for this.

Your mock implementation could extend `Connection` as it is not final. What would you gain from an interface?

**Comment by rjd22** [comment]
@derrabus I would gain that I only have to know the interface and not all underlying dependencies like the Driver. Interfaces allow you to Mock the implementation without having to deal with the constructor dependencies and dependencies that are not part of the interface of that implementation. 

Also partial mocks might only implement a part of the interface allowing to return sensible "This method is not supported in this mock" exceptions for methods you don't want to support.

**Comment by derrabus** [comment]
You can do very much the same with a class as well. For example:

https://github.com/doctrine/orm/blob/2.10.x/tests/Doctrine/Tests/Mocks/ConnectionMock.php

**Comment by rjd22** [comment]
I've seen those examples but if you look closely those mocks require are lot of other parts to be mocked your application is not exposed to:

`ConnectionMock`  depends on `DatabasePlatformMock` and `DriverMock` etc...

This requires you to have more in depth knowledge of DBAL than really needed for the limited interface you might be using.

Like I said: It's not impossible to Mock a DBAL connection but it's not easy and supplying interfaces will allow users to write Mocks more easily making the developer experience for testing with DBAL a lot better.

Edit: Often you write multiple mocks for the same thing that might act a little bit more differently. Having to create extra mocks for the dependencies will increase the bc-break surface while your application does not use those parts.

**Comment by morozov** [comment]
Unless you're building a database abstraction, mocking a connection or a database is usually a bad idea since you don't own the logic on the other end. If you use the connection to store and retrieve data, define a repository, mock it to test the application logic, and test the repository via integration tests with a real database.

**Comment by derrabus** [comment]
> I've seen those examples but if you look closely those mocks require are lot of other parts to be mocked your application is not exposed to:
> 
> `ConnectionMock` depends on `DatabasePlatformMock` and `DriverMock` etc...

It depends on those mocks exactly _because_ the library that is tested here interacts with platform and driver as well. The mock implementation that I've linked would pretty much look the same if we provided interfaces.
