### ISSUE TITLE
Create Connection from existing PDO instance

### ISSUE THREAD

**Issue by oojacoboo** [doctrine/dbal#5250]
### BC Break Report

Prior to version 3, you could set the `pdo` property of the `Doctrine\DBAL\Connection` params.  This allowed for you to reuse a PDO connection object.

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.3

#### Summary

The issue here is that you no longer have a way to reuse a connection with Doctrine.  I guess the idea now is that you should initialize your PDO connection with Doctrine, then use the new `getNativeConnection` method.

Please reference this ticket as well: https://github.com/doctrine/dbal/issues/4603.

Even if you overload the `_conn` property via reflection, you're still left with the error mentioned in this ticket.

> SQLSTATE[HY000]: General error: user-supplied statement class must be derived from PDOStatement

The `Doctrine\DBAL\Driver\PDO\Statement` class doesn't extend `PDOStatement`.

**Comment by greg0ire** [comment]
> Prior to version 3

Not meant as a critic, but as a hint to other readers: I was looking at the 3.3.0 changelog in order to find where we did that BC-break and then I noticed that you're reporting a BC-break:
- for a major version;
- that is already documented.

I think it really is a good thing that we merged https://github.com/doctrine/dbal/pull/5247 because it will make people more likely to pick "support question" for that kind of case.


Also for other readers: here is the PR where we deprecated doing this: https://github.com/doctrine/dbal/pull/3554

That PR mentions another fix:

> Another fix for 2 is to implement your own Driver that is created with an existing PDO instance.

Does this help?

**Comment by oojacoboo** [comment]
@greg0ire thanks for some supporting documentation on this.  There wasn't much out there about this topic, so I created a ticket.  It wasn't clear that this was an intentional deprecation and not a BC break.  I'm not happy about it and disagree with how it's done, but I digress.  Closing this, hopefully it's helpful to others with the same issue.
