### ISSUE TITLE
Removed type exception on migration

### ISSUE THREAD

**Issue by hdumazeau** [doctrine/dbal#5335]
### Bug Report
Version 3.3.3

I have updated my project packages including doctrine/dbal
I replaced the use of json_array by json.
When I play the migration of my project to migrate the type json_array to  json, I get an exception: Doctrine\DBAL\Exception / Unknown column type "json_array" requested.

I have identified why I have this exception, as the json_array type is no longer declared, the type no longer exists.

What is the solution to this error in my case

**Comment by andrew-demb** [comment]
I think you should update the type from `json_array` to `json` and migrate DB schema before updating DBAL major version.

After migration, you can update DBAL.

**Comment by mdevlamynck** [comment]
Maybe this should be moved to `doctrine/migration`. Having to update in two steps kind of defeat the purpose of having migrations in the first place. If I understand correctly your suggestion, we should first migrate the DB and deploy it to production then upgrade DBAL and deploy it to production (also it means we can't run migrations from scratch anymore). Furthermore I'm puzzled as to why running the migration triggers this error, I'd expect the migration command to only run the sql in the migration classes and nothing more. Why is it manipulating DBAL types?

**Comment by andrew-demb** [comment]
Major update of the library requires solving BC breaks before updating.

I'm assuming that the DBAL update "accidentally" came to you with `composer update` (because DBAL was a transitive dependency with no explicit version requirements in the application).
To avoid "accidental" major version updates, you need to explicitly set the requirement for a valid version in composer.json and check for deprecated functionality before upgrading.

I don't think `doctrine/migration` should try to handle these cases. Not all deprecations may be automatically solved without developer decisions.

______
> If I understand correctly your suggestion, we should first migrate the DB and deploy it to production then upgrade DBAL and deploy it to production (also it means we can't run migrations from scratch anymore). 

It may depend on how you used json_array. If this was a use with `doctrine/orm` in the entity, then you need to change the column type in the `doctrine/orm` mapping settings for the entity, generate the migration, and only then update DBAL.
In this case, there is no problem with running migrations from scratch.
