### ISSUE TITLE
How to get connections defined in doctrine.yaml?

### ISSUE THREAD

**Issue by bluemoonljb** [doctrine/dbal#5386]
We defined multiple connections in doctrine.yaml, is there a way to get a list of all connections and their params?

Seems in doctrine 1, there is a getConnections() method, but not in doctrine 2 anymore?
Thanks for any help in advance.

**Comment by morozov** [comment]
Hi, we try to keep Github issues for bug reports and feature requests only. If you have a question, please ask it on Stack Overflow or in one of the channels mentioned at https://www.doctrine-project.org/community/index.html

This is probably the wrong repository for this question since Doctrine DBAL doesn't support the usage of YAML configuration.
