### ISSUE TITLE
Migration with multiple schemas failed

### ISSUE THREAD

**Issue by DevdevdevA** [doctrine/dbal#5700]
Hello,
before describing my problem, I want to apologize in advance if I did not post my problem on the right repository.
I hesitated with the Symfony repo directly.

**Environnement:**
- php 8.1
- symfony 5.4
- doctrine/dbal 3.3
- doctrine/doctrine-bundle 2.7
- doctrine/migrations 3.5.1
- postgresql 14.4

**My problem is the following;**
We have a database containing several schema to separate the data useful to the system and those published directly to users.
We use of course the classic entity declaration with Symfony & Doctrine:
```php
/**
 * @ORM\Table(name="stats", schema="system")
 * @ORM\Entity(repositoryClass="App\Repository\System\StatsRepository")
 */
class Stats
``` 

The problem is that when we delete a relation between the `public` schema and the `system` schema, the migration generated by the command `bin/console doctrine:schema:update` has an error when deleting the index.
**Here is the migration generated:**
```php
    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX idx_2225600edc6d4b4b');
        $this->addSql('ALTER TABLE system.stats DROP article_id');
    }
```
The problem being that in deleting the index, the line forgets to specify that the index comes from the `system` schema.
**We need:**
```php
$this->addSql('DROP INDEX system.idx_2225600edc6d4b4b');
```

We want to keep the `bin/console doctrine:schema:update` operation for updating the database, but this problem now forces us to use the migration system to change the drop index. 

I know that the obvious solution would be to use the migration system (`bin/console make:migration`) but this implies some changes in the IC. That's why I'm wondering; **have you ever had this problem? If yes, how did you solve the problem?**

**Comment by morozov** [comment]
So far, the problem isn't scoped to a single repository since it uses the APIs from Doctrine DBAL and Doctrine Migrations, while the schema diff generation indeed happens in Doctrine DBAL.

For it to be actionable on the DBAL side, it needs to be reproduced in terms of the DBAL without additional dependencies. So far, it is not clear what the "relation between the `public` schema and the `system` schema" is and how is removed. I assume it maps to a foreign key on the DBAL side. The definition of the table in the `public` schema is also missing.
