### ISSUE TITLE
array elements are not wrapped with quotation marks in the "IN" expression 

### ISSUE THREAD

**Issue by hdimo** [doctrine/dbal#5792]
### Bug Report

array elements are not wrapped with quotation marks in the "IN" expression 

|    Q        |   A
|------------ | ------
| Version     | 3.5

#### Summary

when executing the bellow code with `$ar = array('test')` , it throws exception with message :

```php
$qb->expr()->in('column', $ar)
```

``_An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column_``

it's not wrapping the items inside array with quotes  "'";

#### Current behaviour

it returns `IN (test)`

#### Expected behaviour

`IN ('test')`

**Comment by morozov** [comment]
The elements of the array passed to `in()` are SQL expressions, not values. Please see the method documentation: https://github.com/doctrine/dbal/blob/35741d682240193b4403e3e1e6bad3cfeffa055e/src/Query/Expression/ExpressionBuilder.php#L282-L290

Instead of passing the values, you need to pass prepared statement parameter placeholders and then bind the values to them. Alternatively, you can pass an array of SQL expressions that quote the literals in question.
