### ISSUE TITLE
Doctrine DBAL query result data types for json and timestamp are converted to string

### ISSUE THREAD

**Issue by beri14** [doctrine/dbal#5805]
|    Q        |   A
|------------ | -----
| Version     | 3.3.2

### Support Question

n a Symfony project I am working, we're trying to use Doctrine DBAL and get rid of it's ORM. But we have stumbled upon an issue where the query result data types seem to not be converted to their PHP values. The data types that are not being converted as we have noticed are json and timestamp (date types), which are converted to string and not to their corresponding types as configured in the Doctrine type mappings.

This is a simple query example we are executing:

```
$query = $this->connection->executeQuery('SELECT * from registration');
$res = $query->fetchAllAssociative();
```
And the result for the two types mentioned above is this: as you see nationalities is a string as is the phone_number_confirmed_at.
```
  [
    "nationalities" => "["DE","NO"]"
    "phone_number_confirmed_at" => "2022-10-18 11:25:55"
  ]
```
nationalities should be an array and the phone_number_confirmed_at field should be a datetime object.

Can these values be converted to their corresponding PHP values? Is there a solution to this?

I have tried adding explicit mapping types to the doctrine.yaml config file like this, expecting it would convert the result data type but with no success:
```
mapping_types:
  timestamp: datetime
```

**Comment by derrabus** [comment]
> But we have stumbled upon an issue where the query result data types seem to not be converted to their PHP values.

Automagically converting query result fields is not what the DBAL does. The code in your example works as expected and documented.

> Can these values be converted to their corresponding PHP values?

Yes, you can do that. You need to know which type you expect for each result field and then fetch the corresponding type object using `Doctrine\DBAL\Types\Type::getType()`. This object should expose a `convertToPHPValue()` method that performs the conversion for a single value for you.

But this is all manual work because the DBAL cannot guess the result field types of arbitrary SQL queries.

> Is there a solution to this?

There is. It's the ORM.
