### ISSUE TITLE
Sqlite: no write permission when create database

### ISSUE THREAD

**Issue by karrakoliko** [doctrine/dbal#6115]
### Support Question

When we **create** sqlite database (whether using symfony console `symfony console doctrine:database:create`, or using doctrine-migrations `vendor/bin/doctrine-migrations migrations:migrate`) created database file has permissions `-rw-r--r--`.

Sqlite database file has no write permission, so it is **read-only by default**.

So, if we try insert some row into db right after migrations run, we get exception:
`An exception occurred while executing a query: SQLSTATE[HY000]: General error: 8 attempt to write a readonly database`

In my case, after first-run of migrations, i have to run `chmod 775` and `chown ${USER}:www-data path/to/db.sqlite` on my db file to be able to insert something in db.

Is it expected behavior?
Why doctrine does not ensure that db is writeable?

**Comment by greg0ire** [comment]
> Sqlite database file has no write permission

> `-rw-r--r--`

The `w` stands for write, doesn't it?

**Comment by karrakoliko** [comment]
> > Sqlite database file has no write permission
> 
> > `-rw-r--r--`
> 
> The `w` stands for write, doesn't it?

it does, but for user, not www-data group (what is needed for work by default)

**Comment by derrabus** [comment]
But we cannot anticipate which file permissions you need on your SQLite file, can we?

**Comment by karrakoliko** [comment]
Could you explain me why:
1. when i do ```php -a ... touch('file.db');``` i get fie with `-rw-rw-r--`, owned by `${USER}:${USER}`
2. when i do ```file_put_contents(...)``` inside some symfony controller action, i get file with `-rw-rw-rw-`, owned by `www-data:www-data`
3. but when doctrine creates database, i get database file with `-rw-r--r--`, owned by `${USER}:${USER}` (with **no** `write` permission for group)?

IMO, we definitely can expect that database file is **intended to be writable** for `www-data`, and **not to be read-only** for user running php.

Is my expectation valid?

Is there a way configure rights/owner for database file, created by doctrine?

**Comment by derrabus** [comment]
First of all, files are always owned by the user/group that owned the process that created the file. This explains why files created by a web controller are owned by the web server's user and files created by a shell command are owned by your login user.

> when doctrine creates database

The thing is, DBAL does not create the actual database file, SQLite does. So the behavior you're observing is actually the behavior of SQLite. You can see for yourself by running either…

```php
new SQLite3('/path/to/file.db');
```

… or…

```php
new PDO('sqlite:/path/to/file.db');
```

(Replace `/path/to/` with the actual path under which you want the file to be created, obviously.)

> IMO, we definitely can expect that database file is **intended to be writable** for `www-data`, and **not to be read-only** for user running php.

Absolutely not. To create the database, you're running PHP on the shell under your login user. How should the PHP process know what user and group your web server runs on and how could it possibly anticipate that this specific file is meant to be owned by the web server group instead of the current user's?

> Is there a way configure rights/owner for database file, created by doctrine?

No. You will need to run `chown`/`chmod` yourself after creating the database.

**Comment by karrakoliko** [comment]
@derrabus clear enough, thank you!
