### ISSUE TITLE
Why is there a difference in speed between queries with parameters and without parameters?

### ISSUE THREAD

**Issue by sanhpotter** [doctrine/dbal#6142]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.6.6

#### Summary

Why is there a difference in speed between queries with parameters and without parameters?

#### Current behaviour
- Image 1: query with parameters
  
<img width="1780" alt="Screenshot 2023-09-02 at 11 13 43" src="https://github.com/doctrine/dbal/assets/6468702/356e3486-9bc9-4f5a-9177-094e7d79e4b2">

- Query without parameters

<img width="1783" alt="Screenshot 2023-09-02 at 11 14 14" src="https://github.com/doctrine/dbal/assets/6468702/e774c4ea-856c-4d2e-a353-8e2349fef256">

#### How to reproduce
- Os: linux
- Mysql 5.6

#### Expected behaviour
- Expect the two queries to have the same speed

**Comment by greg0ire** [comment]
"query with parameters" probably means the DBAL ends up resorting to a prepared statement. Here is the relevant piece of code, in case you want to check if this is what is happening:

https://github.com/doctrine/dbal/blob/69cb431ec647aa5516944ddb8496d36f6d0aba0d/src/Connection.php#L1087-L1099

According to [Wikipedia](https://en.wikipedia.org/wiki/Prepared_statement#cite_note-3):

> On the other hand, if a query is executed only once, server-side prepared statements can be slower because of the additional round-trip to the server.[[](https://en.wikipedia.org/wiki/Prepared_statement#cite_note-3)

Note that I'm not sure if this is a really fair comparison: `SELECT banner_ids, banners_status FROM 'sa_banners' WHERE banners_key = :banners_key;` is not actual SQL. Instead, if you look at the logs of your SQL server, you will probably see something like `PREPARE SELECT banner-ids… blah blah`, and then, later `EXECUTE stmt USING blah blah`. Both queries are separate by a network roundrip that might not be taken into account for the query without parameter.

That being said, I'm going to close since:
- this looks like an SQL question
- the how to reproduce section will not actually help to reproduce anything: you did not provide the PHP code responsible for performing the queries, or for displaying the timings or even show that you were using DBAL.

Please resort to Stack Overflow for that kind of thing.
