### ISSUE TITLE
The length of a MySQL long text column is reported as 0

### ISSUE THREAD

**Issue by bjhijmans** [doctrine/dbal#6149]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.6.3

#### Summary

Long story short, we updated values in our database, and to make sure they didn't exceed their allocated space, we had to trim them to the length of the column. We were very surprised to find that our long text columns were suddenly empty.

Much to our surprise, the schema manager returned 0 as the length of the long text column, causing us to trim the values down to 0 length. Thankfully, no production data was affected this time, but we were really lucky that we caught it in time.

#### Current behaviour

When I ask the length of a long text column, it returns 0.

#### How to reproduce

In Laravel, using MySql 8 and the MySqlSchemaManager. Make a table with a long text column and then run:

```php
DB::connection()->getDoctrineSchemaManager()->introspectTable($table)->getColumn($column)->getLength()
```

#### Expected behaviour

I expected the value 4294967295

I do get that value when I run:

```sql
SELECT COLUMN_NAME, CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = "table" AND COLUMN_NAME = "column"
```

**Comment by derrabus** [comment]
> the schema manager returned 0 as the length of the long text column

MySQL's `TEXT` types don't have a length parameter, unlike `VARCHAR` for instance.

> causing us to trim the values down to 0 length.

Don't do this. Seriously.

> I expected the value 4294967295

I have no idea where that expectation is coming from. Declaring a `LONGTEXT(4294967295)` doesn't make sense.

The purpose of DBALs schema introspection is schema comparison and migration. If you use it for anything else, you're on your own. The schema manager won't tell you how many bytes or characters you can funnel into a given table column. It only tells you how the column is declared, because that what you need to know to perform a comparison.

**Comment by bjhijmans** [comment]
The normal text field does have a length of 65535, so it's at least inconsistent.
