### ISSUE TITLE
Custom type breaks when column type is decimal on MariaDB

### ISSUE THREAD

**Issue by cs278** [doctrine/dbal#6185]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.7.1

#### Summary

When using a custom DBAL type which maps to a `DECIMAL` type in MariaDB the schema comparison always thinks it is incorrect. I did a bisect which identifies 04c3330dcf55a232dede0b467394b35ee46e520a as being the problematic commit.

#### Current behaviour

Schema tool generates an `ALTER TABLE` statement to change the column type to `NUMERIC` which is mapped to `DECIMAL` by MariaDB.

#### How to reproduce

1. `git clone https://gist.github.com/b6fe98ac7060668bd11696581e831050.git`
2. `composer install`
3. Amend `$dsn` inside `test.php`
4. `php -f test.php`
5. Run queries 
6. `php -f test.php` - observe alter table query
7. `composer require doctrine/dbal 3.6.*`
8. `php -f test.php` - observe no query generated

#### Expected behaviour

Schema tool should work as it did in 3.6.7 and not detect any differences.

**Comment by cs278** [comment]
FWIW the following patch fixes the issue for me:

```diff
diff --git a/src/Platforms/AbstractMySQLPlatform.php b/src/Platforms/AbstractMySQLPlatform.php
index d1e3e5aff..f1fa73163 100644
--- a/src/Platforms/AbstractMySQLPlatform.php
+++ b/src/Platforms/AbstractMySQLPlatform.php
@@ -1087,7 +1087,7 @@ public function getFloatDeclarationSQL(array $column)
      */
     public function getDecimalTypeDeclarationSQL(array $column)
     {
-        return parent::getDecimalTypeDeclarationSQL($column) . $this->getUnsignedDeclaration($column);
+        return str_replace('NUMERIC(', 'DECIMAL(', parent::getDecimalTypeDeclarationSQL($column)) . $this->getUnsignedDeclaration($column);
     }
 
     /**
```

**Comment by derrabus** [comment]
cc @cgknx

**Comment by cgknx** [comment]
The issue is caused when checking commented column types where the column declaration used is a synonym of the MySQL/MariaDb internal column type names. The simplest approach to fixing this is to restrict the type checking of commented columns to json only which is the only case this test should be necessary.

Changing the column declaration to the internal type as per your patch also works but there is nothing to stop a custom type hard wiring NUMERIC into the type declaration and triggering the issue. 

see PR #6189

**Comment by gregor-tb** [comment]
Maybe the same issue #4981
