### ISSUE TITLE
Design Pattern and Naming Issue

### ISSUE THREAD

**Issue by Nerogee** [doctrine/dbal#6239]
|    Q        |   A
|------------ | -----
| Version     | 3.7.2

### Support Question

I upgrade Symfony from 4.4 to 5.4 along with many other packages. Doctrine related modules are also upgraded. Previously, When I try to get the first row of the result, I did it the following way.

`$rawSql = "SELECT * FROM table where id=:id";

$preparedStatement = DBConnection->prepare($rawSql );

$firstRow = $preparedStatement->execute(['id'=>1])->fetch();
`

The above returned value is an associative array representing the first item. 

After upgrade, it suggests to use method of DBConnection directly. such as **executeQuery**, **fetchAllAssociative** and **fetchOne**. New style of the above example become somethings similar to this:

`
$firstRow = $DBConnection->fetchOne($rawSql ,['id'=>1] );
`

The new style wraps the preparedStatement inside the connection method, and this chance is good to me. But the above **fetchOne** method does not do the job I expected.

Quoting the method introduction here:

`
     * Prepares and executes an SQL query and returns the value of a single column
     * of the first row of the result.
`

With this, it now explains why it does not work the way I thought. Because It returns the single column of the first row of the result. A big question from me is why method like this would help ? and for what situation? Secondly, why there is no equivalence of the old **fetch** method which I think it could be very useful in many situation?  I know I can use the **fetchAssociative**. The one that confused me is that the design/name become worse. Or maybe I'm out dated. 

Similar problem to the method **fetchAllAssociativeIndexed**, quoting from the source code

`     * Prepares and executes an SQL query and returns the result as an associative array with the keys mapped
     * to the first column and the values being an associative array representing the rest of the columns
     * and their values.
 `

I'm not sure how many can fully understand the returned data structure by reading the above method doc. But when I dive a bit deep, I found it is totally unnecessary to have that method for following reasons

1. real-life use case of what that method tries to help is uncommon. 
2.  The job of this method should be left to be done on the business logic layer by developers
3. In case if some developers really need result in that structure. It's not intuitive that developers will expect it out of the box. Why? because that takes a bit time to explain the purpose. Just like the way we read the method doc. Therefore, developers who need result to be in that structure, they will build it themselves. And it's not hard to achieve I believe.
4. The method itself there only to make the source code bloated.

I raised these questions is to find out whether that's only me who felt a bit lost or anybody else more or less agree on my reasoning. If you interested, check this case out [[this](https://github.com/symfony/symfony/pull/44789)](https://github.com/symfony/symfony/pull/44789) which is another case I found things become worst.

**Comment by greg0ire** [comment]
> A big question from me is why method like this would help ? and for what situation?

It would help if you need a single value from the database. Getting an array such as `[42]` in that case is not great, is it?

> Secondly, why there is no equivalence of the old fetch method which I think it could be very useful in many situation? 

Probably because `fetch` is ambiguous? With that name, you can't tell if you're going to get an associative array or not.

> The one that confused me is that the design/name become worse.

Why do you feel it's worse? IMO it's better to have 3 separate methods than one that changes the type of its return value based on a parameter

> Or maybe I'm out dated.

Sorry but, maybe you are indeed, because this opinion is not just mine. It was cited in a talk at SymfonyCon about static analysis.

> real-life use case of what that method tries to help is uncommon.

I think I remember encountering that use-case several times myself, so it's probably not that uncommon.

> The job of this method should be left to be done on the business logic layer by developers

Why?

> In case if some developers really need result in that structure. It's not intuitive that developers will expect it out of the box. Why? because that takes a bit time to explain the purpose. Just like the way we read the method doc. Therefore, developers who need result to be in that structure, they will build it themselves. And it's not hard to achieve I believe.

Maybe you have a point in that the phpdoc could be made more understandable. But otherwise, I disagree that they would not expect it out of the box. Having a unique identifier in a table is mandatory, and therefore super common. Having a result indexed by that identifier is therefore very useful. The phpdoc might be improve to say that this first column will typically be a unique identifier to help developers realise what this is used for.

> The method itself there only to make the source code bloated.

I do not understand this sentence. Does it miss a word?

> I raised these questions is to find out whether that's only me who felt a bit lost or anybody else more or less agree on my reasoning

Mostly disagree, except maybe on the phpdoc.

> If you interested, check https://github.com/symfony/symfony/pull/44789 case out [this](https://github.com/symfony/symfony/pull/44789) which is another case I found things become worst.

This is a Symfony issue… :thinking:

**Comment by derrabus** [comment]
We've changed these methods a long time ago and with the experience we've gathered so far, I believe we can call it a good change.
