### ISSUE TITLE
Custom driver and ExceptionConverter

### ISSUE THREAD

**Issue by gitomato** [doctrine/dbal#6317]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         |no

#### Summary

When writing a custom driver, at some point we need to implement [ExceptionConverter](https://github.com/doctrine/dbal/blob/4.0.x/src/Driver/API/ExceptionConverter.php) interface.

The `convert()` method requires to return a [DriverException](https://github.com/doctrine/dbal/blob/4.0.x/src/Exception/DriverException.php).
However this class is marked as internal and triggers a warning:

> The "Doctrine\DBAL\Exception\DriverException::__construct()" method is considered internal. It may change without further notice. You should not extend it from "App\DBAL\Exception\DriverException".

Could you consider returning the `Doctrine\DBAL\Driver\Exception` interface instead in the future?

PS: thanks for you amazing work!

**Comment by derrabus** [comment]
> The `convert()` method requires to return a [DriverException](https://github.com/doctrine/dbal/blob/4.0.x/src/Exception/DriverException.php). However this class is marked as internal and triggers a warning:
> 
> > The "Doctrine\DBAL\Exception\DriverException::__construct()" method is considered internal. It may change without further notice. You should not extend it from "App\DBAL\Exception\DriverException".

We should probably not flag the constructor as `@internal`. I'm open to removing this annotation on 4.1.x because custom drivers need to call that constructor. Please send a PR.

That being said: this might not be the only "internal" API you will need to call for your custom driver. Please keep opening issues if you run into more of them. ✌🏻 

> Could you consider returning the `Doctrine\DBAL\Driver\Exception` interface instead in the future?

That's a terrible idea. The whole point of the exception converter is to upcast an exception specific to your database to one of the well-known exceptions that extend `DriverException`. If the converter returned anything else, the wrapper layer or the application wouldn't know what to do with that exception.
