### ISSUE TITLE
PostgreSQL option gssencmode=disable isn't configurable

### ISSUE THREAD

**Issue by hacfi** [doctrine/dbal#6319]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.8.2

#### Summary

On macOS there is an issue with PostgreSQL which can only be fixed by setting `gssencmode=disable` on the PDO connect. This isn't supported currently.

#### Current behaviour

No way to configure gssencmode=disable.

#### How to reproduce

On a refresh macOS installation install php and postgresql@16 via homebrew. Set up php-fpm and try to connect to PostgreSQL. Results in a segfault.

#### Expected behaviour

I can configure gssencmode=disable and connect to PostgreSQL.

**Comment by derrabus** [comment]
Is this option part of the PDO DSN? I'm asking because it's not documented [here](https://www.php.net/manual/en/ref.pdo-pgsql.connection.php). But I can find it [in the Postgres documentation](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-GSSENCMODE).

I assume this also affects the pgsql driver?

Please send a PR that adds the option to both drivers.

**Comment by hacfi** [comment]
Not sure about this but will try to figure it out. I found the solution in this PHP issue: https://github.com/php/php-src/issues/13339#issuecomment-1950205780

Not sure yet if pgsql driver is also affected but will try to reproduce this when I find some time. After having lost 3 days at work I need to catch up on some tasks first.

**Comment by hacfi** [comment]
I checked and the pgsql driver is also affected. I noticed pgsql isn't easily configurable with the Doctrine bundle so I created an issue for that (https://github.com/doctrine/DoctrineBundle/issues/1763).

Create the PR #6320 to add this.
